# Vulnerability Exception Policy — SpedireSicuro
#
# Eccezioni documentate per vulnerabilita note che NON devono bloccare la CI.
# Ogni eccezione richiede:
# - CVE/GHSA ID
# - Motivo dell'eccezione (perche non sfruttabile nel nostro contesto)
# - Data di scadenza (massimo 90 giorni dalla data di aggiunta)
# - Owner responsabile della remediation
# - Ticket di riferimento
#
# SLA di patch:
#   CRITICAL = 7 giorni
#   HIGH     = 30 giorni
#
# Revisione: primo lunedi di ogni mese
# Approvazione: richiede review da almeno 1 membro del team security
#
# NOTA: questo file e' documentazione di processo.
# npm audit non supporta allowlist native — se servira automazione,
# aggiungere uno script che filtra `npm audit --json` contro queste eccezioni.

exceptions: []
# Esempio:
# - id: "GHSA-xxxx-yyyy-zzzz"
#   package: "example-package"
#   version: ">=1.0.0 <1.2.3"
#   severity: "high"
#   reason: "Non sfruttabile: input validato server-side, nessun user input raggiunge il path vulnerabile"
#   added: "2026-02-19"
#   expires: "2026-05-19"
#   owner: "team-security"
#   ticket: "#1234"
